export const EVENT_TYPES = [
  'bill_filed',
  'bill_cosponsored',
  'congress_urgency',
  'committee_hearing_scheduled',
  'committee_markup_scheduled',
  'witness_list_posted',
  'witness_statement_posted',
  'bill_text_updated',
  'bill_summary_published',
  'bill_referred_to_committee',
  'bill_reported_from_committee',
  'floor_vote_scheduled',
  'roll_call_vote_recorded',
  'crs_report_published',
  'war_powers_signal',
  'civil_confinement_signal',
  'detention_infrastructure_signal',
  'surveillance_authority_signal',
  'data_center_environment_signal',
  'executive_action',
  'court_order',
  'injunction',
  'hearing_scheduled',
  'hearing_missed',
  'deposition_missed',
  'subpoena_issued',
  'subpoena_ignored',
  'contempt_threat',
  'watchdog_lawsuit',
  'ethics_probe',
  'resignation',
  'statement_claim',
  'official_statement',
  'vote_called',
  'vote_failed',
  'funding_exposure',
  'contradiction',
  'investigation_opened',
  'sanctions_action',
  'military_action',
  'policy_change',
  'generic_report',
] as const;

export type EventType = (typeof EVENT_TYPES)[number];

/**
 * Deterministic severity weighting (0..1) for global promotion.
 * Keep these explicit + tunable — do not hide behind opaque scoring.
 */
export const EVENT_SEVERITY: Record<EventType, number> = {
  injunction: 1.0,
  court_order: 0.92,
  congress_urgency: 0.84,
  roll_call_vote_recorded: 0.86,
  committee_markup_scheduled: 0.82,
  committee_hearing_scheduled: 0.78,
  witness_statement_posted: 0.76,
  bill_reported_from_committee: 0.74,
  floor_vote_scheduled: 0.74,
  surveillance_authority_signal: 0.74,
  detention_infrastructure_signal: 0.72,
  war_powers_signal: 0.72,
  civil_confinement_signal: 0.7,
  bill_text_updated: 0.68,
  witness_list_posted: 0.66,
  data_center_environment_signal: 0.64,
  bill_referred_to_committee: 0.58,
  bill_summary_published: 0.54,
  crs_report_published: 0.48,
  contempt_threat: 0.9,
  subpoena_ignored: 0.88,
  subpoena_issued: 0.78,
  investigation_opened: 0.78,
  ethics_probe: 0.76,
  resignation: 0.74,
  executive_action: 0.72,
  sanctions_action: 0.7,
  military_action: 0.7,
  watchdog_lawsuit: 0.68,
  policy_change: 0.62,
  funding_exposure: 0.6,
  contradiction: 0.58,
  vote_failed: 0.56,
  vote_called: 0.52,
  bill_filed: 0.5,
  bill_cosponsored: 0.46,
  hearing_missed: 0.46,
  deposition_missed: 0.46,
  hearing_scheduled: 0.42,
  official_statement: 0.28,
  statement_claim: 0.22,
  generic_report: 0.3,
};

