import 'server-only';

import type { SignalSourceConfig } from '@/lib/intel/types';

const WH_NEWS = 'https://www.whitehouse.gov/news/feed/';
const WH_PRESIDENTIAL = 'https://www.whitehouse.gov/presidential-actions/feed/';
const FR_PUBLISHED =
  'https://www.federalregister.gov/api/v1/documents.json?per_page=25&order=newest';
const FR_PI =
  'https://www.federalregister.gov/api/v1/public-inspection-documents.json?per_page=25&order=newest';
const GOVINFO_BILLS = 'https://www.govinfo.gov/rss/bills.xml';
/** Verified 200 OK; this is full CREC RSS — not the Daily Digest (crec-dd URL 404 on GovInfo). */
const GOVINFO_CREC = 'https://www.govinfo.gov/rss/crec.xml';
const SCOTUSBLOG = 'https://www.scotusblog.com/feed/';
/** Listing page; articles are CPT `alerts` under /news-alerts/{slug}/ (RSS unreliable in some fetch runtimes). */
const DEMOCRACY_DOCKET = 'https://www.democracydocket.com/news-alerts/';
const LAWFARE = 'https://www.lawfaremedia.org/feeds/articles';
const PROPUBLICA = 'https://feeds.propublica.org/propublica/main';
const AMERICAN_OVERSIGHT = 'https://americanoversight.org/feed';
const COURIER_COVER_UP = 'https://thecoverupnewsletter.substack.com/feed';
const ROBERT_REICH = 'https://robertreich.substack.com/feed';
const ON_OFFENSE = 'https://onoffense.substack.com/feed';
const TOTAL_HYPOCRISY = 'https://totalhypocrisy.substack.com/feed';
/** Disabled: HTTP 200 but RSS parses to 0 items in our pipeline; same project uses Substack (`courier-the-cover-up`). */
const UNCOVERING_EPSTEIN_NETWORK_FEED = 'https://epsteincoverup.us/feed/';

/** Renamed department; public RSS (was defense.gov). */
const WAR_GOV_NEWS_RSS =
  'https://www.war.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=945';
/** English-only “all” feed (site `/rss/all` is mixed-language; `/rss/en/all` matches footer link on meduza.io/en). */
const MEDUZA_EN_RSS = 'https://meduza.io/rss/en/all';
/** Verified `application/rss+xml`; U.S. Air Force public news releases. */
const AF_MIL_NEWS_RSS = 'https://www.af.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=1';
const MAG_972_RSS = 'https://www.972mag.com/feed/';
const BIRN_RSS = 'https://balkaninsight.com/feed/';
const RAPPLER_RSS = 'https://www.rappler.com/rss/';
const BELLINGCAT_RSS = 'https://www.bellingcat.com/feed/';
const FORBIDDEN_STORIES_RSS = 'https://forbiddenstories.org/feed/';
/** Optional: Kyiv Independent has no stable public RSS on the main site; set INTEL_KYIV_INDEPENDENT_RSS_URL when you have a working feed URL. */
const KYIV_INDEPENDENT_RSS =
  typeof process !== 'undefined' && process.env.INTEL_KYIV_INDEPENDENT_RSS_URL
    ? String(process.env.INTEL_KYIV_INDEPENDENT_RSS_URL).trim()
    : '';
const BLS_SCHEDULE_2026 = 'https://www.bls.gov/schedule/2026/home.htm';
const BEA_NEWS_SCHEDULE = 'https://www.bea.gov/news/schedule';
const USNI_FLEET_TAG_PAGE = 'https://news.usni.org/tag/fleet-tracker/';
const HOUSE_JUDICIARY_GOP_PRESS = 'https://judiciary.house.gov/media/press-releases';
const HOUSE_JUDICIARY_DEM_PRESS =
  'https://democrats-judiciary.house.gov/media-center/press-releases';

/** Routine Federal Register / PI churn — suppressed from default desk surface (retained in DB). */
const FR_PROCEDURAL_BLOCK_KEYWORDS = [
  'sunshine act',
  'federal advisory committee',
  'agency information collection',
  'paperwork reduction act',
  'submission for omb review',
  'notice of submission for omb review',
  'renewal of previously approved',
  'delegation of authority',
  'charter filed',
  'charter renewal',
  'meeting notice',
  'public hearing',
  'national environmental policy act',
  'nepa scoping',
  'privacy act of 1974',
  'system of records',
  'rate adjustment',
  'postal service',
];

/**
 * Version-controlled registry. Reuters/AP: set INTEL_REUTERS_RSS_URL / INTEL_AP_RSS_URL or sources stay disabled (fail closed).
 */
export function getSignalSources(): SignalSourceConfig[] {

  return [
    {
      slug: 'wh-news',
      name: 'White House — News',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: WH_NEWS,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      trustWarningText:
        'Official White House channel: authentic provenance, but messaging is source-controlled and politically interested. Treat as a primary claim surface; verify key factual assertions independently.',
      purpose: 'Official White House news and press releases as syndicated on whitehouse.gov.',
      trustedFor: 'Primary statements of administration messaging and links to published press materials.',
      notTrustedFor: 'Independent fact verification, statutory text, or court holdings.',
      editorialControls: {
        defaultPriority: 52,
        preferredStateChangeTypes: ['press_statement'],
        blockKeywords: [
          'photo opportunity',
          'president trump welcomes',
          'president biden welcomes',
          'president trump honors',
          'participates in the swearing-in',
          'participates in a swearing-in',
          'easter egg roll',
          'pardon ceremony',
          'medal of freedom',
        ],
        allowKeywords: [
          'executive order',
          'national security',
          'immigration',
          'tariff',
          'federal workforce',
          'emergency',
        ],
        noiseNotes:
          'High share of ceremonial and photo-op posts; block list targets recurring low-materiality headlines.',
        relevanceNotes:
          'Allow keywords lightly boost substantive policy hooks; does not override provenance tier on the desk.',
      },
    },
    {
      slug: 'wh-presidential',
      name: 'White House — Presidential Actions',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: WH_PRESIDENTIAL,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      trustWarningText:
        'Official White House channel: authentic provenance for executive actions, but framing can be self-protective or strategic. Verify descriptive claims and impacts with independent sources.',
      purpose: 'Presidential actions and orders as published on the White House site feed.',
      trustedFor: 'Detecting new presidential actions and canonical links to official pages.',
      notTrustedFor: 'Legal analysis, judicial review, or final regulatory text.',
      editorialControls: {
        defaultPriority: 64,
        preferredStateChangeTypes: ['presidential_action'],
        allowKeywords: [
          'executive order',
          'proclamation',
          'memorandum',
          'clemency',
          'pardon',
        ],
        relevanceNotes: 'Presidential-action feed; baseline priority above general WH news.',
      },
    },
    {
      slug: 'fr-public-inspection',
      name: 'Federal Register — Public Inspection',
      provenanceClass: 'PRIMARY',
      fetchKind: 'json_api',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: FR_PI,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Federal Register Public Inspection filings before official publication.',
      trustedFor: 'Pre-publication regulatory and notice filings with FR metadata.',
      notTrustedFor: 'Final authoritative text; use the published Federal Register feed.',
      editorialControls: {
        defaultPriority: 36,
        preferredStateChangeTypes: ['pre_publication'],
        blockKeywords: [...FR_PROCEDURAL_BLOCK_KEYWORDS],
        allowKeywords: ['proposed rule', 'interim final', 'executive order', 'sanctions', 'immigration'],
        noiseNotes:
          'Public Inspection is broad; procedural notices are suppressed so higher-signal filings surface first.',
      },
    },
    {
      slug: 'fr-published',
      name: 'Federal Register — Published',
      provenanceClass: 'PRIMARY',
      fetchKind: 'json_api',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: FR_PUBLISHED,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Official published Federal Register documents via the public API.',
      trustedFor: 'Published rules, notices, and documents with document numbers and HTML URLs.',
      notTrustedFor: 'Breaking narrative without reading the linked document.',
      editorialControls: {
        defaultPriority: 38,
        preferredStateChangeTypes: ['published_document'],
        blockKeywords: [...FR_PROCEDURAL_BLOCK_KEYWORDS],
        allowKeywords: [
          'final rule',
          'interim final rule',
          'executive order',
          'presidential document',
          'sanctions',
          'immigration',
          'securities',
        ],
        noiseNotes:
          'Published FR remains fully ingested; procedural / administrative notices are suppressed from the default desk.',
      },
    },
    {
      slug: 'govinfo-bills',
      name: 'GovInfo — Bills (RSS)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: GOVINFO_BILLS,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'GovInfo RSS for bill-related packages and updates.',
      trustedFor: 'Legislative pointers and GovInfo bill syndication.',
      notTrustedFor: 'Floor outcomes or vote certainty without Congress.gov or the Record.',
      editorialControls: {
        defaultPriority: 44,
        preferredStateChangeTypes: ['legislative_feed_item'],
        noiseNotes:
          'RSS is volumetric; default priority below presidential actions and below specialist courts feeds.',
      },
    },
    {
      slug: 'govinfo-crec',
      name: 'GovInfo — Congressional Record (RSS)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: GOVINFO_CREC,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Congressional Record material as published through GovInfo RSS.',
      trustedFor: 'Record pointers and GovInfo syndication of CREC content.',
      notTrustedFor: 'Substituting for every Congress.gov status edge case or same-day vote tabulation.',
      editorialNotes:
        'Full CREC RSS from GovInfo. A Daily Digest–specific RSS was not available at the crec-dd path (404); replace if GovInfo documents a DD feed.',
      notes:
        'Full CREC RSS from GovInfo. Daily Digest-specific RSS was not available at crec-dd path (404); replace if GovInfo documents a DD feed.',
      editorialControls: {
        defaultPriority: 40,
        preferredStateChangeTypes: ['congressional_record_feed_item'],
        blockKeywords: ['prayer of the guest chaplain', 'adjournment'],
        noiseNotes: 'Full CREC RSS is extremely high volume; light block list for obvious procedural chaff.',
      },
    },
    {
      slug: 'house-judiciary-press-gop',
      name: 'House Judiciary (Majority) — Press Releases',
      provenanceClass: 'PRIMARY',
      fetchKind: 'html_index',
      deskLane: 'osint',
      sourceFamily: 'claims_public',
      contentUseMode: 'metadata_only',
      endpointUrl: HOUSE_JUDICIARY_GOP_PRESS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      trustWarningText:
        'Official committee communications: authentic provenance, but source-controlled framing. Treat as a claims surface for committee actions; verify key assertions with filings, transcripts, and corroborating reporting.',
      purpose: 'Committee press releases for oversight actions (subpoenas, letters, hearings) and official statements.',
      trustedFor: 'Noticing new committee actions and official committee posture.',
      notTrustedFor: 'Independent verification of factual claims or legal conclusions.',
      editorialControls: {
        defaultPriority: 56,
        allowKeywords: ['subpoena', 'contempt', 'hearing', 'deposition', 'letter', 'investigation', 'probe'],
        blockKeywords: ['weekly schedule', 'icymi'],
        noiseNotes: 'Press releases are messaging-heavy; allow list focuses on oversight verbs.',
      },
    },
    {
      slug: 'house-judiciary-press-dem',
      name: 'House Judiciary (Minority) — Press Releases',
      provenanceClass: 'PRIMARY',
      fetchKind: 'html_index',
      deskLane: 'osint',
      sourceFamily: 'claims_public',
      contentUseMode: 'metadata_only',
      endpointUrl: HOUSE_JUDICIARY_DEM_PRESS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      trustWarningText:
        'Official committee communications: authentic provenance, but source-controlled framing. Treat as a claims surface for committee actions; verify key assertions with filings, transcripts, and corroborating reporting.',
      purpose: 'Minority press releases that can surface oversight requests, hearing contexts, and documented evidence releases.',
      trustedFor: 'Noticing minority-side oversight signals and public document drops.',
      notTrustedFor: 'Independent verification of factual claims or legal conclusions.',
      editorialControls: {
        defaultPriority: 54,
        allowKeywords: ['hearing', 'testimony', 'demand', 'documents', 'investigation', 'oversight'],
        blockKeywords: ['statement on', 'remarks before'],
        noiseNotes: 'Keeps messaging-heavy items present but below primary records and corroborated reporting.',
      },
    },
    {
      slug: 'scotusblog',
      name: 'SCOTUSblog',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: SCOTUSBLOG,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Specialist coverage of Supreme Court docket activity and opinions.',
      trustedFor: 'Docket context and expert analysis around Court business.',
      notTrustedFor: 'Binding holdings; always use Court slip opinions and orders.',
      editorialControls: {
        defaultPriority: 56,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['opinion', 'order', 'certiorari', 'argument'],
      },
    },
    {
      slug: 'democracy-docket',
      name: 'Democracy Docket',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'html_index',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: DEMOCRACY_DOCKET,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Specialist election and voting-rights litigation reporting.',
      trustedFor: 'Case narrative and filings in the democracy and voting-rights space.',
      notTrustedFor: 'Final judicial disposition without the underlying court documents.',
      editorialNotes:
        'Ingest uses the public /news-alerts/ HTML index (article links), not RSS. Titles are derived from URL slugs until a richer parser is added.',
      editorialControls: {
        defaultPriority: 58,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['lawsuit', 'opinion', 'appeals', 'ballot', 'redistrict', 'voting'],
      },
    },
    {
      slug: 'lawfare',
      name: 'Lawfare',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: LAWFARE,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'National security, courts, and executive-power legal analysis from Lawfare (public site RSS).',
      trustedFor: 'Timely specialist framing and links to primary documents cited in their coverage.',
      notTrustedFor: 'Substitute for court orders, statutes, or agency final rules.',
      editorialControls: {
        defaultPriority: 54,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['court', 'executive', 'congress', 'surveillance', 'election', 'immigration', 'DOJ'],
      },
    },
    {
      slug: 'propublica',
      name: 'ProPublica',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: PROPUBLICA,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Investigative reporting feed (nonprofit, public interest).',
      trustedFor: 'Leads and accountability journalism pointers with canonical article links.',
      notTrustedFor: 'Treating RSS blurbs alone as proof; always read the full investigation at ProPublica.',
      editorialNotes:
        'Included in the default manifest; RSS blurbs are pointers—read full investigations on site.',
      editorialControls: {
        defaultPriority: 57,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['lawsuit', 'records', 'court', 'Trump', 'agency', 'investigation'],
      },
    },
    {
      slug: 'american-oversight',
      name: 'American Oversight',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: AMERICAN_OVERSIGHT,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'FOIA litigation and government accountability updates from American Oversight’s public feed.',
      trustedFor: 'Records-request narratives, lawsuit filings, and transparency campaign pointers.',
      notTrustedFor: 'Verified contents of unreleased records; read linked filings and releases.',
      editorialNotes:
        'Included in the default manifest; specialist FOIA and accountability feed.',
      editorialControls: {
        defaultPriority: 55,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['lawsuit', 'records', 'FOIA', 'transparency', 'court', 'ICE', 'DOJ'],
      },
    },
    {
      slug: 'courier-the-cover-up',
      name: 'The Cover-Up (COURIER / Substack)',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'preview_and_link',
      endpointUrl: COURIER_COVER_UP,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose:
        'Optional specialist newsletter on Epstein accountability (public Substack RSS). Enabled in manifest; preview-and-link only.',
      trustedFor: 'Syndicated headlines and links to COURIER’s own publication.',
      notTrustedFor: 'Law enforcement evidence or complete document sets; not a substitute for court records.',
      editorialNotes: 'Preview-and-link only; enabled in default manifest.',
      editorialControls: {
        defaultPriority: 50,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'uncovering-epstein-network',
      name: 'Uncovering the Epstein Network',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'preview_and_link',
      endpointUrl: UNCOVERING_EPSTEIN_NETWORK_FEED,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose:
        'Registry row for the epsteincoverup.us project; RSS ingest disabled because /feed/ does not yield items in our parser. Use The Cover-Up Substack (`courier-the-cover-up`) for the working feed; canonical web pages remain on the main site.',
      trustedFor: 'Headlines, dates, and pointers to the site’s own reporting pages (when ingested via another path).',
      notTrustedFor: 'Court filings or law-enforcement evidence; read linked articles and primary sources.',
      editorialNotes:
        'Disabled as RSS: duplicate of the same editorial project as courier-the-cover-up, and the site feed is not reliable here. Revisit as html_index on /coverage/ if canonical on-domain links are required.',
      editorialControls: {
        defaultPriority: 52,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['Epstein', 'DOJ', 'court', 'files', 'network'],
      },
    },
    {
      slug: 'robert-reich',
      name: 'Robert Reich (Substack)',
      provenanceClass: 'COMMENTARY',
      fetchKind: 'rss',
      deskLane: 'voices',
      sourceFamily: 'general',
      contentUseMode: 'preview_and_link',
      endpointUrl: ROBERT_REICH,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Creator commentary and economic/political framing via public Substack RSS.',
      trustedFor: 'Interpretation hooks and pointers to the author’s own posts.',
      notTrustedFor: 'Primary government records, wire confirmation, or neutral fact baseline.',
      editorialNotes:
        'Commentary lane; included in default manifest (voices desk).',
      editorialControls: {
        defaultPriority: 46,
        preferredStateChangeTypes: ['commentary_item'],
        allowKeywords: ['Trump', 'democracy', 'economy', 'oligarch', 'worker'],
      },
    },
    {
      slug: 'on-offense-kris-goldsmith',
      name: 'On Offense with Kris Goldsmith',
      provenanceClass: 'COMMENTARY',
      fetchKind: 'rss',
      deskLane: 'voices',
      sourceFamily: 'general',
      contentUseMode: 'preview_and_link',
      endpointUrl: ON_OFFENSE,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose:
        'Substack publication feed used to discover new On Offense episode posts and link back to canonical pages.',
      trustedFor: 'Episode/post titles, dates, canonical post URLs, and short previews.',
      notTrustedFor: 'Wire news or official documents; audio is consumed on the creator platform.',
      editorialControls: {
        defaultPriority: 48,
        preferredStateChangeTypes: ['commentary_item'],
      },
    },
    {
      slug: 'total-hypocrisy',
      name: 'Total Hypocrisy (Substack)',
      provenanceClass: 'COMMENTARY',
      fetchKind: 'rss',
      deskLane: 'voices',
      sourceFamily: 'general',
      contentUseMode: 'preview_and_link',
      endpointUrl: TOTAL_HYPOCRISY,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Creator commentary via Substack public RSS when verified (enable after confirming feed returns items).',
      trustedFor: 'Syndicated post titles and links to Substack.',
      notTrustedFor: 'Patreon-exclusive audio without a separate public feed.',
      editorialNotes:
        'Enabled in default manifest; verify feed in production if items look wrong. Patreon-only podcast is not ingested here.',
      editorialControls: {
        defaultPriority: 45,
        preferredStateChangeTypes: ['commentary_item'],
      },
    },

    // --- Statements lane (direct claims / public-import scaffold; not OSINT evidence) ---
    {
      slug: 'statements-public-import',
      name: 'Statements — public import (placeholder)',
      provenanceClass: 'COMMENTARY',
      fetchKind: 'manual',
      deskLane: 'statements',
      sourceFamily: 'claims_public',
      contentUseMode: 'manual_review',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'high',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'Adapter placeholder for future public post URLs or feed-like imports (no login-only scraping in this milestone).',
      trustedFor: 'Nothing by itself — claims require corroboration from primary records or reporting.',
      notTrustedFor: 'Treating reposted claims as evidence; substituting for court orders or official releases.',
      editorialNotes:
        'Lane is isolated from OSINT ranking; keep disabled until a concrete public-ingest path is approved.',
      trustWarningText:
        'Direct claims and political statements can spread misinformation. This lane is claims-only, not evidence.',
    },
    {
      slug: 'statements-rss-sandbox',
      name: 'Statements — RSS sandbox (disabled)',
      provenanceClass: 'COMMENTARY',
      fetchKind: 'rss',
      deskLane: 'statements',
      sourceFamily: 'claims_public',
      contentUseMode: 'feed_summary',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'high',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'Optional future hook for a vetted, public, high-signal RSS of political claims (disabled until editorial sign-off).',
      trustedFor: 'Canonical links to public posts when explicitly enabled.',
      notTrustedFor: 'Firehose partisan feeds or unvetted aggregators.',
      editorialNotes: 'Disabled by default to avoid turning the lane into undifferentiated social noise.',
      trustWarningText: 'Claims-only lane: not evidence; verify against primary sources.',
    },

    // --- Defense / operations desk (separate lane) ---
    {
      slug: 'war-gov-releases',
      name: 'U.S. Department of War — News (RSS)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'defense_ops',
      sourceFamily: 'defense_primary',
      contentUseMode: 'feed_summary',
      endpointUrl: WAR_GOV_NEWS_RSS,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      trustWarningText:
        'Official U.S. military press channel: authentic provenance for releases, but claims are source-controlled and operationally framed. Cross-check with independent reporting when assessing battlefield or political narratives.',
      purpose: 'Department of War public news RSS (successor branding to defense.gov syndication).',
      trustedFor: 'Official U.S. military press releases, statements, and links to published materials.',
      notTrustedFor: 'Independent verification of combat outcomes or adversary intent.',
      editorialControls: {
        defaultPriority: 50,
        preferredStateChangeTypes: ['press_statement'],
        allowKeywords: ['exercise', 'deployment', 'strike', 'sanctions', 'NATO', 'Ukraine', 'Taiwan', 'carrier'],
      },
    },
    {
      slug: 'usni-fleet-tracker',
      name: 'USNI News — Fleet / Marine tracker (listing)',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'html_index',
      deskLane: 'defense_ops',
      sourceFamily: 'defense_specialist',
      contentUseMode: 'metadata_only',
      endpointUrl: USNI_FLEET_TAG_PAGE,
      // Disabled: returns 403 from server/runtime fetch (bot-blocked), which breaks ingest.
      // Re-enable only after confirming the URL returns 200 from Vercel/cron runtime (not just a browser).
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'USNI News posts tagged fleet-tracker (approximate carrier/amphib positions from open sources — not primary operational orders).',
      trustedFor: 'Public maritime posture context and specialist summaries with canonical USNI links.',
      notTrustedFor: 'Real-time operational tasking or classified position data.',
      editorialNotes:
        'Disabled: endpoint returns 403 to ingest runtime (bot-blocked). Previously: ingest uses the public tag listing HTML; titles may be slug-derived where the index omits text.',
      editorialControls: {
        defaultPriority: 44,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['fleet', 'carrier', 'marine', 'tracker', 'amphibious'],
      },
    },
    {
      slug: 'af-mil-news',
      name: 'U.S. Air Force — News (RSS)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'defense_ops',
      sourceFamily: 'defense_primary',
      contentUseMode: 'feed_summary',
      endpointUrl: AF_MIL_NEWS_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      trustWarningText:
        'Official U.S. Air Force channel: authentic provenance for releases; operational claims remain source-controlled.',
      purpose: 'Department of the Air Force public news RSS (installations, exercises, releases).',
      trustedFor: 'Official USAF press releases and announcements with canonical links.',
      notTrustedFor: 'Independent verification of contested operational claims.',
      editorialNotes: 'RSS URL verified 200 with application/rss+xml; monitor for .mil rate limits in cron.',
      editorialControls: {
        defaultPriority: 48,
        preferredStateChangeTypes: ['press_statement'],
        allowKeywords: ['exercise', 'deployment', 'strike', 'space', 'bomber', 'fighter'],
      },
    },
    {
      slug: 'army-mil-news',
      name: 'U.S. Army — News RSS (placeholder)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'defense_ops',
      sourceFamily: 'defense_primary',
      contentUseMode: 'feed_summary',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      purpose:
        'Placeholder: legacy army.mil RSS paths vary; confirm a working feed URL (often DVIDS or a DesktopModules RSS) before enabling.',
      trustedFor: 'Official Army public releases when a stable RSS is confirmed.',
      notTrustedFor: 'Enabling until the feed is verified in production (curl + parse smoke test).',
      editorialNotes:
        'Disabled: many .mil RSS endpoints return 403/404 to automated probes; set a verified URL after manual check.',
    },
    {
      slug: 'centcom-press',
      name: 'CENTCOM — Press/media RSS (placeholder)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'defense_ops',
      sourceFamily: 'combatant_command',
      contentUseMode: 'feed_summary',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      purpose:
        'Placeholder for a CENTCOM public RSS or HTML index path; many centcom.mil endpoints block automated fetches (403).',
      trustedFor: 'Official U.S. Central Command communications when a stable feed is wired.',
      notTrustedFor: 'Operational truth without cross-check; not enabled until URL is verified.',
      editorialNotes:
        'Deferred: confirm an RSS that returns 200 from the ingest runtime (not just browser); consider html_index fallback.',
    },
    {
      slug: 'eucom-press',
      name: 'U.S. European Command — Press RSS (placeholder)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'defense_ops',
      sourceFamily: 'combatant_command',
      contentUseMode: 'feed_summary',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      purpose:
        'Placeholder for EUCOM / USEUCOM public press RSS; domain often returns 403 to datacenter crawlers.',
      trustedFor: 'Official combatant-command messaging once a working feed is confirmed.',
      notTrustedFor: 'Enabling without a verified ingest smoke test.',
      editorialNotes:
        'Deferred: pair with manual verification or alternate host (e.g. defense.gov cross-posts) before enabling.',
    },
    {
      slug: 'dvids-sandbox',
      name: 'DVIDS — Tagged feed (disabled; firehose risk)',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'defense_ops',
      sourceFamily: 'defense_specialist',
      contentUseMode: 'feed_summary',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'Reserved for a tightly scoped DVIDS RSS (unit or tag); broad DVIDS feeds are too noisy for this desk by default.',
      trustedFor: 'Curated unit output when a narrow, stable RSS URL is configured.',
      notTrustedFor: 'General DVIDS “all news” ingestion without a narrow tag.',
      editorialNotes:
        'Disabled: DVIDS global feeds are a firehose; enable only with a vetted tag/organization URL and editorial notes.',
    },

    // --- Watchdogs / global independent desk ---
    {
      slug: 'kyiv-independent',
      name: 'The Kyiv Independent',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: KYIV_INDEPENDENT_RSS || null,
      isEnabled: Boolean(KYIV_INDEPENDENT_RSS),
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'English-language Ukraine reporting (enable by setting INTEL_KYIV_INDEPENDENT_RSS_URL to a working RSS URL).',
      trustedFor: 'Regional on-the-ground reporting pointers with outbound canonical links.',
      notTrustedFor: 'Single-source confirmation of front-line claims without corroboration.',
      editorialNotes:
        'Fail-closed when env unset: the public site does not expose a reliable default RSS in all environments.',
      editorialControls: {
        defaultPriority: 46,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['Ukraine', 'Kyiv', 'Russia', 'missile', 'drone', 'Zelensky'],
      },
    },
    {
      slug: 'meduza-english',
      name: 'Meduza — English RSS',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: MEDUZA_EN_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'Independent Russian / post-Soviet coverage in English (`/rss/en/all` — not the mixed-language `/rss/all`).',
      trustedFor: 'Alternative regional narrative and investigation leads with canonical links.',
      notTrustedFor: 'Substitute for primary documents or wire confirmation.',
      editorialControls: {
        defaultPriority: 45,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'mag-972',
      name: '+972 Magazine',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: MAG_972_RSS,
      // Disabled: redirects loop in fetch runtime (eventually "redirect count exceeded" / "fetch failed"), taking down cron.
      // Re-enable after confirming the feed resolves without redirect loops from the server runtime.
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'Israel–Palestine reporting from Palestinian and Israeli journalists.',
      trustedFor: 'On-the-ground context and independent analysis with outbound links.',
      notTrustedFor: 'Legal status of territories or military claims without independent verification.',
      editorialNotes:
        'Disabled: RSS feed redirects loop (adds UTM params and bounces), causing "redirect count exceeded" in ingest runtime.',
      editorialControls: {
        defaultPriority: 45,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'birn-balkaninsight',
      name: 'BIRN — Balkan Insight',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: BIRN_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'Southeastern Europe investigative and regional reporting (Balkan Insight RSS).',
      trustedFor: 'Regional accountability journalism and court/accountability leads.',
      notTrustedFor: 'Substituting for court judgments or official state communications.',
      editorialControls: {
        defaultPriority: 44,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'rappler',
      name: 'Rappler',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: RAPPLER_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'Philippines and Southeast Asia democracy / civil-society coverage.',
      trustedFor: 'Regional reporting pointers with canonical Rappler links.',
      notTrustedFor: 'Election outcomes or court holdings without primary sources.',
      editorialControls: {
        defaultPriority: 44,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'bellingcat',
      name: 'Bellingcat',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: BELLINGCAT_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'OSINT-heavy investigations (munitions, geolocation, flight data, conflict evidence).',
      trustedFor: 'Structured open-source findings and methodology-forward reporting.',
      notTrustedFor: 'Substitute for official investigations or classified assessments.',
      editorialControls: {
        defaultPriority: 48,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'forbidden-stories',
      name: 'Forbidden Stories',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: FORBIDDEN_STORIES_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'Cross-border collaborative investigations when local journalists are silenced.',
      trustedFor: 'Investigation launches and consortium reporting pointers.',
      notTrustedFor: 'Treating consortium summaries as complete evidence packages.',
      editorialControls: {
        defaultPriority: 44,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'occrp',
      name: 'OCCRP',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'unsupported',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'manual_review',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'Registry placeholder: OCCRP public RSS endpoints are often bot-blocked. Prefer manual review, Aleph workflows, or a stable partner RSS URL when available.',
      trustedFor: 'Cross-border corruption and asset-trail investigations when ingested.',
      notTrustedFor: 'Automated ingest without verifying the endpoint in your environment.',
      editorialNotes: 'Enable after confirming a fetchable RSS or JSON listing URL; do not assume occrp.org/en/rss works from all server IPs.',
    },

    // --- Indicators / scheduled releases ---
    {
      slug: 'bls-release-calendar',
      name: 'BLS — Release calendar (HTML index)',
      provenanceClass: 'SCHEDULE',
      fetchKind: 'html_index',
      deskLane: 'indicators',
      sourceFamily: 'indicator_hard',
      contentUseMode: 'metadata_only',
      endpointUrl: BLS_SCHEDULE_2026,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'BLS publication schedule page — extracts news.release links (CPI, employment, etc.).',
      trustedFor: 'Upcoming BLS statistical release pointers.',
      notTrustedFor: 'Actual figures; always read the published release.',
      editorialControls: {
        defaultPriority: 40,
        preferredStateChangeTypes: ['scheduled_release'],
      },
    },
    {
      slug: 'bea-release-schedule',
      name: 'BEA — News release schedule (HTML index)',
      provenanceClass: 'SCHEDULE',
      fetchKind: 'html_index',
      deskLane: 'indicators',
      sourceFamily: 'indicator_hard',
      contentUseMode: 'metadata_only',
      endpointUrl: BEA_NEWS_SCHEDULE,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'BEA release schedule — extracts /news/ links (GDP, PCE, trade).',
      trustedFor: 'Upcoming BEA macro release pointers.',
      notTrustedFor: 'Advance estimates vs revisions; read the release.',
      editorialControls: {
        defaultPriority: 40,
        preferredStateChangeTypes: ['scheduled_release'],
      },
    },
    {
      slug: 'sam-gov-contracting',
      name: 'SAM.gov — Contracting (placeholder)',
      provenanceClass: 'SCHEDULE',
      fetchKind: 'unsupported',
      deskLane: 'indicators',
      sourceFamily: 'indicator_hard',
      contentUseMode: 'manual_review',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose:
        'Placeholder for future SAM.gov Opportunities API or award feeds (requires API key / ToS review — not wired in this milestone).',
      trustedFor: 'Defense and federal contracting opportunity/award discovery when implemented.',
      notTrustedFor: 'Automated award interpretation without reading solicitations.',
    },
    {
      slug: 'ofac-recent-actions',
      name: 'OFAC — Recent actions (placeholder)',
      provenanceClass: 'SCHEDULE',
      fetchKind: 'unsupported',
      deskLane: 'indicators',
      sourceFamily: 'indicator_hard',
      contentUseMode: 'manual_review',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'normal',
      purpose:
        'Placeholder: legacy OFAC RSS was retired; monitor recent-actions pages, email alerts, or partner feeds manually.',
      trustedFor: 'Sanctions and designation updates when ingested via a supported path.',
      notTrustedFor: 'Legal compliance determinations without counsel.',
    },
    {
      slug: 'indicator-pentagon-pizza',
      name: 'Pentagon Pizza Index (anecdotal)',
      provenanceClass: 'SCHEDULE',
      fetchKind: 'manual',
      deskLane: 'indicators',
      sourceFamily: 'indicator_anecdotal',
      contentUseMode: 'manual_review',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      indicatorClass: 'anecdotal',
      trustWarningMode: 'none',
      trustWarningLevel: 'high',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'Registry-only humorous/anecdotal “thermometer” signal (restaurant traffic near the Pentagon). Do not ingest automatically; pair with hard indicators only in UI.',
      trustedFor: 'Cultural / meme context only.',
      notTrustedFor: 'Any operational or policy inference.',
    },
  ];
}
