import 'server-only';

import type { SignalSourceConfig } from '@/lib/intel/types';

const WH_NEWS = 'https://www.whitehouse.gov/news/feed/';
const WH_PRESIDENTIAL = 'https://www.whitehouse.gov/presidential-actions/feed/';
const FR_PUBLISHED =
  'https://www.federalregister.gov/api/v1/documents.json?per_page=25&order=newest';
const FR_PI =
  'https://www.federalregister.gov/api/v1/public-inspection-documents.json?per_page=25&order=newest';
const GOVINFO_BILLS = 'https://www.govinfo.gov/rss/bills.xml';
/** Verified 200 OK; this is full CREC RSS — not the Daily Digest (crec-dd URL 404 on GovInfo). */
const GOVINFO_CREC = 'https://www.govinfo.gov/rss/crec.xml';
const SCOTUSBLOG = 'https://www.scotusblog.com/feed/';
/** Listing page; articles are CPT `alerts` under /news-alerts/{slug}/ (RSS unreliable in some fetch runtimes). */
const DEMOCRACY_DOCKET = 'https://www.democracydocket.com/news-alerts/';
const LAWFARE = 'https://www.lawfaremedia.org/feeds/articles';
const PROPUBLICA = 'https://feeds.propublica.org/propublica/main';
const AMERICAN_OVERSIGHT = 'https://americanoversight.org/feed';
const COURIER_COVER_UP = 'https://thecoverupnewsletter.substack.com/feed';
const ROBERT_REICH = 'https://robertreich.substack.com/feed';
const ON_OFFENSE = 'https://onoffense.substack.com/feed';
const TOTAL_HYPOCRISY = 'https://totalhypocrisy.substack.com/feed';

/** Renamed department; public RSS (was defense.gov). */
const WAR_GOV_NEWS_RSS =
  'https://www.war.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=945';
/** English-only “all” feed (site `/rss/all` is mixed-language; `/rss/en/all` matches footer link on meduza.io/en). */
const MEDUZA_EN_RSS = 'https://meduza.io/rss/en/all';
/** Verified `application/rss+xml`; U.S. Air Force public news releases. */
const AF_MIL_NEWS_RSS = 'https://www.af.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=1';
/** Army CORE static RSS; organization id 1 is the Army homepage. */
const ARMY_MIL_NEWS_RSS = 'https://www.army.mil/rss/static/1.xml';
const MAG_972_HOME = 'https://www.972mag.com/';
const BIRN_RSS = 'https://balkaninsight.com/feed/';
const RAPPLER_RSS = 'https://www.rappler.com/rss/';
const BELLINGCAT_RSS = 'https://www.bellingcat.com/feed/';
const FORBIDDEN_STORIES_RSS = 'https://forbiddenstories.org/feed/';
const KYIV_INDEPENDENT_NEWS_ARCHIVE_DEFAULT = 'https://www.kyivindependent.com/news-archive/';
/**
 * Optional override: set INTEL_KYIV_INDEPENDENT_LISTING_URL to a vetted alternate public listing URL
 * (html_index). This replaces the prior RSS default, because `/feed/` now returns 404 in the ingest runtime.
 */
const KYIV_INDEPENDENT_LISTING_URL = (() => {
  if (typeof process === 'undefined') return KYIV_INDEPENDENT_NEWS_ARCHIVE_DEFAULT;
  const raw = process.env.INTEL_KYIV_INDEPENDENT_LISTING_URL;
  const trimmed = typeof raw === 'string' ? raw.trim() : '';
  return trimmed || KYIV_INDEPENDENT_NEWS_ARCHIVE_DEFAULT;
})();
const USNI_FLEET_TAG_PAGE = 'https://news.usni.org/tag/fleet-tracker/';
const EUCOM_ARTICLES_RSS = 'https://www.eucom.mil/syndication-feed/rss/articles';
const CENTCOM_PRESS_RELEASES_LISTING = 'https://www.centcom.mil/MEDIA/PRESS-RELEASES/';
const HOUSE_JUDICIARY_GOP_PRESS = 'https://judiciary.house.gov/media/press-releases';
const HOUSE_JUDICIARY_DEM_PRESS =
  'https://democrats-judiciary.house.gov/media-center/press-releases';
const ISW_FEEDS_PAGE = 'https://www.understandingwar.org/feeds2';

/** Routine Federal Register / PI churn — suppressed from default desk surface (retained in DB). */
const FR_PROCEDURAL_BLOCK_KEYWORDS = [
  'sunshine act',
  'federal advisory committee',
  'agency information collection',
  'paperwork reduction act',
  'submission for omb review',
  'notice of submission for omb review',
  'renewal of previously approved',
  'delegation of authority',
  'charter filed',
  'charter renewal',
  'meeting notice',
  'public hearing',
  'national environmental policy act',
  'nepa scoping',
  'privacy act of 1974',
  'system of records',
  'rate adjustment',
  'postal service',
];

/**
 * Version-controlled registry. Reuters/AP: set INTEL_REUTERS_RSS_URL / INTEL_AP_RSS_URL or sources stay disabled (fail closed).
 */
export function getSignalSources(): SignalSourceConfig[] {

  return [
    {
      slug: 'wh-news',
      name: 'White House — News',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: WH_NEWS,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      trustWarningText:
        'Official White House channel: authentic provenance, but messaging is source-controlled and politically interested. Treat as a primary claim surface; verify key factual assertions independently.',
      purpose: 'Official White House news and press releases as syndicated on whitehouse.gov.',
      trustedFor: 'Primary statements of administration messaging and links to published press materials.',
      notTrustedFor: 'Independent fact verification, statutory text, or court holdings.',
      editorialControls: {
        defaultPriority: 52,
        preferredStateChangeTypes: ['press_statement'],
        blockKeywords: [
          'photo opportunity',
          'president trump welcomes',
          'president biden welcomes',
          'president trump honors',
          'participates in the swearing-in',
          'participates in a swearing-in',
          'easter egg roll',
          'pardon ceremony',
          'medal of freedom',
        ],
        allowKeywords: [
          'executive order',
          'national security',
          'immigration',
          'tariff',
          'federal workforce',
          'emergency',
        ],
        noiseNotes:
          'High share of ceremonial and photo-op posts; block list targets recurring low-materiality headlines.',
        relevanceNotes:
          'Allow keywords lightly boost substantive policy hooks; does not override provenance tier on the desk.',
      },
    },
    {
      slug: 'wh-presidential',
      name: 'White House — Presidential Actions',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: WH_PRESIDENTIAL,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      trustWarningText:
        'Official White House channel: authentic provenance for executive actions, but framing can be self-protective or strategic. Verify descriptive claims and impacts with independent sources.',
      purpose: 'Presidential actions and orders as published on the White House site feed.',
      trustedFor: 'Detecting new presidential actions and canonical links to official pages.',
      notTrustedFor: 'Legal analysis, judicial review, or final regulatory text.',
      editorialControls: {
        defaultPriority: 64,
        preferredStateChangeTypes: ['presidential_action'],
        allowKeywords: [
          'executive order',
          'proclamation',
          'memorandum',
          'clemency',
          'pardon',
        ],
        relevanceNotes: 'Presidential-action feed; baseline priority above general WH news.',
      },
    },
    {
      slug: 'fr-public-inspection',
      name: 'Federal Register — Public Inspection',
      provenanceClass: 'PRIMARY',
      fetchKind: 'json_api',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: FR_PI,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Federal Register Public Inspection filings before official publication.',
      trustedFor: 'Pre-publication regulatory and notice filings with FR metadata.',
      notTrustedFor: 'Final authoritative text; use the published Federal Register feed.',
      editorialControls: {
        defaultPriority: 36,
        preferredStateChangeTypes: ['pre_publication'],
        blockKeywords: [...FR_PROCEDURAL_BLOCK_KEYWORDS],
        allowKeywords: ['proposed rule', 'interim final', 'executive order', 'sanctions', 'immigration'],
        noiseNotes:
          'Public Inspection is broad; procedural notices are suppressed so higher-signal filings surface first.',
      },
    },
    {
      slug: 'fr-published',
      name: 'Federal Register — Published',
      provenanceClass: 'PRIMARY',
      fetchKind: 'json_api',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: FR_PUBLISHED,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Official published Federal Register documents via the public API.',
      trustedFor: 'Published rules, notices, and documents with document numbers and HTML URLs.',
      notTrustedFor: 'Breaking narrative without reading the linked document.',
      editorialControls: {
        defaultPriority: 38,
        preferredStateChangeTypes: ['published_document'],
        blockKeywords: [...FR_PROCEDURAL_BLOCK_KEYWORDS],
        allowKeywords: [
          'final rule',
          'interim final rule',
          'executive order',
          'presidential document',
          'sanctions',
          'immigration',
          'securities',
        ],
        noiseNotes:
          'Published FR remains fully ingested; procedural / administrative notices are suppressed from the default desk.',
      },
    },
    {
      slug: 'govinfo-bills',
      name: 'GovInfo — Bills (RSS)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: GOVINFO_BILLS,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'GovInfo RSS for bill-related packages and updates.',
      trustedFor: 'Legislative pointers and GovInfo bill syndication.',
      notTrustedFor: 'Floor outcomes or vote certainty without Congress.gov or the Record.',
      editorialControls: {
        defaultPriority: 44,
        preferredStateChangeTypes: ['legislative_feed_item'],
        noiseNotes:
          'RSS is volumetric; default priority below presidential actions and below specialist courts feeds.',
      },
    },
    {
      slug: 'govinfo-crec',
      name: 'GovInfo — Congressional Record (RSS)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: GOVINFO_CREC,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Congressional Record material as published through GovInfo RSS.',
      trustedFor: 'Record pointers and GovInfo syndication of CREC content.',
      notTrustedFor: 'Substituting for every Congress.gov status edge case or same-day vote tabulation.',
      editorialNotes:
        'Full CREC RSS from GovInfo. A Daily Digest–specific RSS was not available at the crec-dd path (404); replace if GovInfo documents a DD feed.',
      notes:
        'Full CREC RSS from GovInfo. Daily Digest-specific RSS was not available at crec-dd path (404); replace if GovInfo documents a DD feed.',
      editorialControls: {
        defaultPriority: 40,
        preferredStateChangeTypes: ['congressional_record_feed_item'],
        blockKeywords: ['prayer of the guest chaplain', 'adjournment'],
        noiseNotes: 'Full CREC RSS is extremely high volume; light block list for obvious procedural chaff.',
      },
    },
    {
      slug: 'house-judiciary-press-gop',
      name: 'House Judiciary (Majority) — Press Releases',
      provenanceClass: 'PRIMARY',
      fetchKind: 'html_index',
      deskLane: 'osint',
      sourceFamily: 'claims_public',
      contentUseMode: 'metadata_only',
      endpointUrl: HOUSE_JUDICIARY_GOP_PRESS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      trustWarningText:
        'Official committee communications: authentic provenance, but source-controlled framing. Treat as a claims surface for committee actions; verify key assertions with filings, transcripts, and corroborating reporting.',
      purpose: 'Committee press releases for oversight actions (subpoenas, letters, hearings) and official statements.',
      trustedFor: 'Noticing new committee actions and official committee posture.',
      notTrustedFor: 'Independent verification of factual claims or legal conclusions.',
      editorialControls: {
        defaultPriority: 56,
        allowKeywords: ['subpoena', 'contempt', 'hearing', 'deposition', 'letter', 'investigation', 'probe'],
        blockKeywords: ['weekly schedule', 'icymi'],
        noiseNotes: 'Press releases are messaging-heavy; allow list focuses on oversight verbs.',
      },
    },
    {
      slug: 'house-judiciary-press-dem',
      name: 'House Judiciary (Minority) — Press Releases',
      provenanceClass: 'PRIMARY',
      fetchKind: 'html_index',
      deskLane: 'osint',
      sourceFamily: 'claims_public',
      contentUseMode: 'metadata_only',
      endpointUrl: HOUSE_JUDICIARY_DEM_PRESS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      trustWarningText:
        'Official committee communications: authentic provenance, but source-controlled framing. Treat as a claims surface for committee actions; verify key assertions with filings, transcripts, and corroborating reporting.',
      purpose: 'Minority press releases that can surface oversight requests, hearing contexts, and documented evidence releases.',
      trustedFor: 'Noticing minority-side oversight signals and public document drops.',
      notTrustedFor: 'Independent verification of factual claims or legal conclusions.',
      editorialControls: {
        defaultPriority: 54,
        allowKeywords: ['hearing', 'testimony', 'demand', 'documents', 'investigation', 'oversight'],
        blockKeywords: ['statement on', 'remarks before'],
        noiseNotes: 'Keeps messaging-heavy items present but below primary records and corroborated reporting.',
      },
    },
    {
      slug: 'scotusblog',
      name: 'SCOTUSblog',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: SCOTUSBLOG,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Specialist coverage of Supreme Court docket activity and opinions.',
      trustedFor: 'Docket context and expert analysis around Court business.',
      notTrustedFor: 'Binding holdings; always use Court slip opinions and orders.',
      editorialControls: {
        defaultPriority: 56,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['opinion', 'order', 'certiorari', 'argument'],
      },
    },
    {
      slug: 'democracy-docket',
      name: 'Democracy Docket',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'html_index',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: DEMOCRACY_DOCKET,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Specialist election and voting-rights litigation reporting.',
      trustedFor: 'Case narrative and filings in the democracy and voting-rights space.',
      notTrustedFor: 'Final judicial disposition without the underlying court documents.',
      editorialNotes:
        'Ingest uses the public /news-alerts/ HTML index (article links), not RSS. Titles are derived from URL slugs until a richer parser is added.',
      editorialControls: {
        defaultPriority: 58,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['lawsuit', 'opinion', 'appeals', 'ballot', 'redistrict', 'voting'],
      },
    },
    {
      slug: 'lawfare',
      name: 'Lawfare',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: LAWFARE,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'National security, courts, and executive-power legal analysis from Lawfare (public site RSS).',
      trustedFor: 'Timely specialist framing and links to primary documents cited in their coverage.',
      notTrustedFor: 'Substitute for court orders, statutes, or agency final rules.',
      editorialControls: {
        defaultPriority: 54,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['court', 'executive', 'congress', 'surveillance', 'election', 'immigration', 'DOJ'],
      },
    },
    {
      slug: 'propublica',
      name: 'ProPublica',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: PROPUBLICA,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Investigative reporting feed (nonprofit, public interest).',
      trustedFor: 'Leads and accountability journalism pointers with canonical article links.',
      notTrustedFor: 'Treating RSS blurbs alone as proof; always read the full investigation at ProPublica.',
      editorialNotes:
        'Included in the default manifest; RSS blurbs are pointers—read full investigations on site.',
      editorialControls: {
        defaultPriority: 57,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['lawsuit', 'records', 'court', 'Trump', 'agency', 'investigation'],
      },
    },
    {
      slug: 'american-oversight',
      name: 'American Oversight',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'feed_summary',
      endpointUrl: AMERICAN_OVERSIGHT,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'FOIA litigation and government accountability updates from American Oversight’s public feed.',
      trustedFor: 'Records-request narratives, lawsuit filings, and transparency campaign pointers.',
      notTrustedFor: 'Verified contents of unreleased records; read linked filings and releases.',
      editorialNotes:
        'Included in the default manifest; specialist FOIA and accountability feed.',
      editorialControls: {
        defaultPriority: 55,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['lawsuit', 'records', 'FOIA', 'transparency', 'court', 'ICE', 'DOJ'],
      },
    },
    {
      slug: 'courier-the-cover-up',
      name: 'The Cover-Up (COURIER / Substack)',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'osint',
      sourceFamily: 'general',
      contentUseMode: 'preview_and_link',
      endpointUrl: COURIER_COVER_UP,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose:
        'Optional specialist newsletter on Epstein accountability (public Substack RSS). Enabled in manifest; preview-and-link only.',
      trustedFor: 'Syndicated headlines and links to COURIER’s own publication.',
      notTrustedFor: 'Law enforcement evidence or complete document sets; not a substitute for court records.',
      editorialNotes: 'Preview-and-link only; enabled in default manifest.',
      editorialControls: {
        defaultPriority: 50,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'robert-reich',
      name: 'Robert Reich (Substack)',
      provenanceClass: 'COMMENTARY',
      fetchKind: 'rss',
      deskLane: 'voices',
      sourceFamily: 'general',
      contentUseMode: 'preview_and_link',
      endpointUrl: ROBERT_REICH,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Creator commentary and economic/political framing via public Substack RSS.',
      trustedFor: 'Interpretation hooks and pointers to the author’s own posts.',
      notTrustedFor: 'Primary government records, wire confirmation, or neutral fact baseline.',
      editorialNotes:
        'Commentary lane; included in default manifest (voices desk).',
      editorialControls: {
        defaultPriority: 46,
        preferredStateChangeTypes: ['commentary_item'],
        allowKeywords: ['Trump', 'democracy', 'economy', 'oligarch', 'worker'],
      },
    },
    {
      slug: 'on-offense-kris-goldsmith',
      name: 'On Offense with Kris Goldsmith',
      provenanceClass: 'COMMENTARY',
      fetchKind: 'rss',
      deskLane: 'voices',
      sourceFamily: 'general',
      contentUseMode: 'preview_and_link',
      endpointUrl: ON_OFFENSE,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose:
        'Substack publication feed used to discover new On Offense episode posts and link back to canonical pages.',
      trustedFor: 'Episode/post titles, dates, canonical post URLs, and short previews.',
      notTrustedFor: 'Wire news or official documents; audio is consumed on the creator platform.',
      editorialControls: {
        defaultPriority: 48,
        preferredStateChangeTypes: ['commentary_item'],
      },
    },
    {
      slug: 'total-hypocrisy',
      name: 'Total Hypocrisy (Substack)',
      provenanceClass: 'COMMENTARY',
      fetchKind: 'rss',
      deskLane: 'voices',
      sourceFamily: 'general',
      contentUseMode: 'preview_and_link',
      endpointUrl: TOTAL_HYPOCRISY,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: false,
      heroEligibilityMode: 'normal',
      purpose: 'Creator commentary via Substack public RSS when verified (enable after confirming feed returns items).',
      trustedFor: 'Syndicated post titles and links to Substack.',
      notTrustedFor: 'Patreon-exclusive audio without a separate public feed.',
      editorialNotes:
        'Enabled in default manifest; verify feed in production if items look wrong. Patreon-only podcast is not ingested here.',
      editorialControls: {
        defaultPriority: 45,
        preferredStateChangeTypes: ['commentary_item'],
      },
    },

    // --- Statements lane (direct claims / public-import scaffold; not OSINT evidence) ---
    {
      slug: 'statements-public-import',
      name: 'Statements — public import (placeholder)',
      provenanceClass: 'COMMENTARY',
      fetchKind: 'manual',
      deskLane: 'statements',
      sourceFamily: 'claims_public',
      contentUseMode: 'manual_review',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'high',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'Adapter placeholder for future public post URLs or feed-like imports (no login-only scraping in this milestone).',
      trustedFor: 'Nothing by itself — claims require corroboration from primary records or reporting.',
      notTrustedFor: 'Treating reposted claims as evidence; substituting for court orders or official releases.',
      editorialNotes:
        'Lane is isolated from OSINT ranking; keep disabled until a concrete public-ingest path is approved.',
      trustWarningText:
        'Direct claims and political statements can spread misinformation. This lane is claims-only, not evidence.',
    },
    {
      slug: 'statements-rss-sandbox',
      name: 'Statements — RSS sandbox (disabled)',
      provenanceClass: 'COMMENTARY',
      fetchKind: 'rss',
      deskLane: 'statements',
      sourceFamily: 'claims_public',
      contentUseMode: 'feed_summary',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'high',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'Optional future hook for a vetted, public, high-signal RSS of political claims (disabled until editorial sign-off).',
      trustedFor: 'Canonical links to public posts when explicitly enabled.',
      notTrustedFor: 'Firehose partisan feeds or unvetted aggregators.',
      editorialNotes: 'Disabled by default to avoid turning the lane into undifferentiated social noise.',
      trustWarningText: 'Claims-only lane: not evidence; verify against primary sources.',
    },

    // --- Defense / operations desk (separate lane) ---
    {
      slug: 'war-gov-releases',
      name: 'U.S. Department of War — News (RSS)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'defense_ops',
      sourceFamily: 'defense_primary',
      contentUseMode: 'feed_summary',
      endpointUrl: WAR_GOV_NEWS_RSS,
      isEnabled: true,
      isCoreSource: true,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      trustWarningText:
        'Official U.S. military press channel: authentic provenance for releases, but claims are source-controlled and operationally framed. Cross-check with independent reporting when assessing battlefield or political narratives.',
      purpose: 'Department of War public news RSS (successor branding to defense.gov syndication).',
      trustedFor: 'Official U.S. military press releases, statements, and links to published materials.',
      notTrustedFor: 'Independent verification of combat outcomes or adversary intent.',
      editorialControls: {
        defaultPriority: 50,
        preferredStateChangeTypes: ['press_statement'],
        allowKeywords: ['exercise', 'deployment', 'strike', 'sanctions', 'NATO', 'Ukraine', 'Taiwan', 'carrier'],
      },
    },
    {
      slug: 'usni-fleet-tracker',
      name: 'USNI News — Fleet / Marine tracker (listing)',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'html_index',
      deskLane: 'defense_ops',
      sourceFamily: 'defense_specialist',
      contentUseMode: 'metadata_only',
      endpointUrl: USNI_FLEET_TAG_PAGE,
      // Keep enabled for visibility; ingest will mark this source failing if bot-blocked.
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'USNI News posts tagged fleet-tracker (approximate carrier/amphib positions from open sources — not primary operational orders).',
      trustedFor: 'Public maritime posture context and specialist summaries with canonical USNI links.',
      notTrustedFor: 'Real-time operational tasking or classified position data.',
      editorialNotes:
        'Known issue: endpoint may return 403 to the ingest runtime (bot-blocked). Ingest uses the public tag listing HTML; titles may be slug-derived where the index omits text.',
      editorialControls: {
        defaultPriority: 44,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['fleet', 'carrier', 'marine', 'tracker', 'amphibious'],
      },
    },
    {
      slug: 'af-mil-news',
      name: 'U.S. Air Force — News (RSS)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'defense_ops',
      sourceFamily: 'defense_primary',
      contentUseMode: 'feed_summary',
      endpointUrl: AF_MIL_NEWS_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      trustWarningText:
        'Official U.S. Air Force channel: authentic provenance for releases; operational claims remain source-controlled.',
      purpose: 'Department of the Air Force public news RSS (installations, exercises, releases).',
      trustedFor: 'Official USAF press releases and announcements with canonical links.',
      notTrustedFor: 'Independent verification of contested operational claims.',
      editorialNotes: 'RSS URL verified 200 with application/rss+xml; monitor for .mil rate limits in cron.',
      editorialControls: {
        defaultPriority: 48,
        preferredStateChangeTypes: ['press_statement'],
        allowKeywords: ['exercise', 'deployment', 'strike', 'space', 'bomber', 'fighter'],
      },
    },
    {
      slug: 'army-mil-news',
      name: 'U.S. Army — News (RSS)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'defense_ops',
      sourceFamily: 'defense_primary',
      contentUseMode: 'feed_summary',
      endpointUrl: ARMY_MIL_NEWS_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      purpose:
        'Official U.S. Army homepage releases via Army CORE static RSS (organization feed).',
      trustedFor: 'Official Army public releases and announcements with canonical Army.mil links.',
      notTrustedFor: 'Independent verification of contested operational claims.',
      editorialNotes:
        'Uses Army CORE static RSS (`/rss/static/1.xml`). If .mil blocks the ingest runtime, treat failures as source-scoped (do not poison the run).',
    },
    {
      slug: 'centcom-press',
      name: 'CENTCOM — Press releases (listing)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'html_index',
      deskLane: 'defense_ops',
      sourceFamily: 'combatant_command',
      contentUseMode: 'metadata_only',
      endpointUrl: CENTCOM_PRESS_RELEASES_LISTING,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      purpose:
        'CENTCOM press releases (listing ingest of canonical press-release URLs; metadata-only).',
      trustedFor: 'Official CENTCOM press-release links and timestamps (as available).',
      notTrustedFor: 'Independent verification of operational claims; treat as source-controlled statements.',
      editorialNotes:
        'Uses html_index on the stable press releases listing (no pagination traversal in ingest). If blocked (403), it should fail source-scoped.',
    },
    {
      slug: 'eucom-press',
      name: 'U.S. European Command — Articles (RSS)',
      provenanceClass: 'PRIMARY',
      fetchKind: 'rss',
      deskLane: 'defense_ops',
      sourceFamily: 'combatant_command',
      contentUseMode: 'feed_summary',
      endpointUrl: EUCOM_ARTICLES_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'source_controlled_official_claims',
      trustWarningLevel: 'caution',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'demote_low_substance',
      purpose:
        'Official USEUCOM syndication RSS for published articles.',
      trustedFor: 'Official EUCOM article links and press-style releases with canonical eucom.mil URLs.',
      notTrustedFor: 'Independent verification of operational claims; source-controlled framing.',
      editorialNotes:
        'Uses eucom.mil syndication feed (`/syndication-feed/rss/articles`). If blocked in runtime, treat failures as source-scoped.',
    },
    {
      slug: 'dvids-sandbox',
      name: 'DVIDS — Tagged feed (disabled; firehose risk)',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'defense_ops',
      sourceFamily: 'defense_specialist',
      contentUseMode: 'feed_summary',
      endpointUrl: null,
      isEnabled: false,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'Reserved for a tightly scoped DVIDS RSS (unit or tag); broad DVIDS feeds are too noisy for this desk by default.',
      trustedFor: 'Curated unit output when a narrow, stable RSS URL is configured.',
      notTrustedFor: 'General DVIDS “all news” ingestion without a narrow tag.',
      editorialNotes:
        'Disabled: DVIDS global feeds are a firehose; enable only with a vetted tag/organization URL and editorial notes.',
    },

    // --- Watchdogs / global independent desk ---
    {
      slug: 'kyiv-independent',
      name: 'The Kyiv Independent',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'html_index',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: KYIV_INDEPENDENT_LISTING_URL,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'English-language Ukraine reporting via public site listing (html_index; override with INTEL_KYIV_INDEPENDENT_LISTING_URL if needed).',
      trustedFor: 'Regional on-the-ground reporting pointers with outbound canonical links.',
      notTrustedFor: 'Single-source confirmation of front-line claims without corroboration.',
      editorialNotes:
        'RSS `/feed/` currently returns 404 in the ingest runtime; adapter uses `/news-archive/` HTML listing and extracts canonical article URLs (titles slug-derived). Keep env override for emergency swaps if the site changes.',
      editorialControls: {
        defaultPriority: 46,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: ['Ukraine', 'Kyiv', 'Russia', 'missile', 'drone', 'Zelensky'],
      },
    },
    {
      slug: 'isw-feeds',
      name: 'Institute for the Study of War — Feeds',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'html_index',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: ISW_FEEDS_PAGE,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'ISW public feeds page covering recurring Ukraine and Iran war updates.',
      trustedFor:
        'High-signal specialist reporting pointers and recurring campaign assessments.',
      notTrustedFor:
        'Single-source confirmation of battlefield or state claims without corroboration.',
      editorialNotes:
        'Uses the public feeds page as html_index to capture recurring “Russian Offensive Campaign Assessment” and “Iran Update” posts.',
      editorialControls: {
        defaultPriority: 47,
        preferredStateChangeTypes: ['specialist_item'],
        allowKeywords: [
          'Ukraine',
          'Russia',
          'Iran',
          'missile',
          'drone',
          'strike',
          'ceasefire',
          'sanctions',
          'nuclear',
        ],
      },
    },
    {
      slug: 'meduza-english',
      name: 'Meduza — English RSS',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: MEDUZA_EN_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'Independent Russian / post-Soviet coverage in English (`/rss/en/all` — not the mixed-language `/rss/all`).',
      trustedFor: 'Alternative regional narrative and investigation leads with canonical links.',
      notTrustedFor: 'Substitute for primary documents or wire confirmation.',
      editorialControls: {
        defaultPriority: 45,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'mag-972',
      name: '+972 Magazine',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'html_index',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: MAG_972_HOME,
      // Keep enabled for visibility; ingest will mark this source failing if redirect loops/bot blocks recur.
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'Israel–Palestine reporting from Palestinian and Israeli journalists.',
      trustedFor: 'On-the-ground context and independent analysis with outbound links.',
      notTrustedFor: 'Legal status of territories or military claims without independent verification.',
      editorialNotes:
        'RSS feed currently self-redirects (loop) in the ingest runtime; adapter uses homepage HTML listing and extracts recent /YYYY/MM/ permalinks. Guard with redirect-loop protections; treat failures as source-scoped.',
      editorialControls: {
        defaultPriority: 45,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'birn-balkaninsight',
      name: 'BIRN — Balkan Insight',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: BIRN_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'Southeastern Europe investigative and regional reporting (Balkan Insight RSS).',
      trustedFor: 'Regional accountability journalism and court/accountability leads.',
      notTrustedFor: 'Substituting for court judgments or official state communications.',
      editorialControls: {
        defaultPriority: 44,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'rappler',
      name: 'Rappler',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: RAPPLER_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'Philippines and Southeast Asia democracy / civil-society coverage.',
      trustedFor: 'Regional reporting pointers with canonical Rappler links.',
      notTrustedFor: 'Election outcomes or court holdings without primary sources.',
      editorialControls: {
        defaultPriority: 44,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'bellingcat',
      name: 'Bellingcat',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: BELLINGCAT_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'OSINT-heavy investigations (munitions, geolocation, flight data, conflict evidence).',
      trustedFor: 'Structured open-source findings and methodology-forward reporting.',
      notTrustedFor: 'Substitute for official investigations or classified assessments.',
      editorialControls: {
        defaultPriority: 48,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'forbidden-stories',
      name: 'Forbidden Stories',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: FORBIDDEN_STORIES_RSS,
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose: 'Cross-border collaborative investigations when local journalists are silenced.',
      trustedFor: 'Investigation launches and consortium reporting pointers.',
      notTrustedFor: 'Treating consortium summaries as complete evidence packages.',
      editorialControls: {
        defaultPriority: 44,
        preferredStateChangeTypes: ['specialist_item'],
      },
    },
    {
      slug: 'occrp',
      name: 'OCCRP',
      provenanceClass: 'SPECIALIST',
      fetchKind: 'rss',
      deskLane: 'watchdogs',
      sourceFamily: 'watchdog_global',
      contentUseMode: 'feed_summary',
      endpointUrl: 'https://www.occrp.org/en/feed',
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'never_hero_without_corroboration',
      purpose:
        'Cross-border corruption investigations (OCCRP public RSS).',
      trustedFor: 'Cross-border corruption and asset-trail investigations when ingested.',
      notTrustedFor: 'Independent verification without corroboration; treat as specialist reporting pointers.',
      editorialNotes:
        'Uses the public OCCRP RSS (`/en/feed`). The prior `?format=feed&type=rss` endpoint returns HTML in the ingest runtime and parses to 0 items.',
    },

    // --- Scheduled releases / reference destinations ---
    {
      slug: 'ofac-recent-actions',
      name: 'OFAC — Recent actions (listing)',
      provenanceClass: 'SCHEDULE',
      fetchKind: 'html_index',
      deskLane: 'osint',
      sourceFamily: 'indicator_hard',
      contentUseMode: 'metadata_only',
      endpointUrl: 'https://ofac.treasury.gov/recent-actions',
      isEnabled: true,
      isCoreSource: false,
      trustWarningMode: 'none',
      trustWarningLevel: 'info',
      requiresIndependentVerification: true,
      heroEligibilityMode: 'normal',
      purpose:
        'OFAC recent actions listing (legacy RSS retired; ingest extracts recent-action detail URLs).',
      trustedFor: 'Sanctions and designation updates when ingested via a supported path.',
      notTrustedFor: 'Legal compliance determinations without counsel.',
      editorialNotes:
        'OFAC retired RSS as of 2025-01-31; html_index on /recent-actions is the correct low-scope adapter. Keep items metadata-only.',
    },
  ];
}
